# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/acer/a4/extract-files.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
    vendor/acer/a4/proprietary/libril.so:obj/lib/libril.so \
    vendor/acer/a4/proprietary/libaudioalsa.so:obj/lib/libaudioalsa.so \
    vendor/acer/a4/proprietary/libcamera.so:obj/lib/libcamera.so \
    vendor/acer/a4/proprietary/liboemcamera.so:obj/lib/liboemcamera.so \

# All the blobs necessary for paso
PRODUCT_COPY_FILES += \
    vendor/acer/a4/proprietary/qwerty.kcm.bin:/system/usr/keychars/qwerty.kcm.bin \
    vendor/acer/a4/proprietary/acer-hs-butt.kcm.bin:/system/usr/keychars/acer-hs-butt.kcm.bin \
    vendor/acer/a4/proprietary/qwerty2.kcm.bin:/system/usr/keychars/qwerty2.kcm.bin \
    vendor/acer/a4/proprietary/AVRCP.kl:/system/usr/keylayout/AVRCP.kl \
    vendor/acer/a4/proprietary/a4-gpio-keypad.kl:/system/usr/keylayout/a4-gpio-keypad.kl \
    vendor/acer/a4/proprietary/acer-hs-butt.kl:/system/usr/keylayout/acer-hs-butt.kl \
    vendor/acer/a4/proprietary/cypress-ts.kl:/system/usr/keylayout/cypress-ts.kl \
    vendor/acer/a4/proprietary/qwerty.kl:/system/usr/keylayout/qwerty.kl \
# ETC
PRODUCT_COPY_FILES += \
    vendor/acer/a4/proprietary/dhcpcd.conf:/system/etc/dhcpcd/dhcpcd.conf \
    vendor/acer/a4/proprietary/01_qcomm_omx.cfg:/system/etc/01_qcomm_omx.cfg \
    vendor/acer/a4/proprietary/voicemail-conf.xml:/system/etc/voicemail-conf.xml \
    vendor/acer/a4/proprietary/init.paso.bt.sh:/system/etc/init.paso.bt.sh \
    vendor/acer/a4/proprietary/acer_ril.db:/system/etc/acer-ril.db \
# ril libs
PRODUCT_COPY_FILES += \
    vendor/acer/a4/proprietary/libauth.so:/system/lib/libauth.so \
    vendor/acer/a4/proprietary/libcm.so:/system/lib/libcm.so \
    vendor/acer/a4/proprietary/libcommondefs.so:/system/lib/libcommondefs.so \
    vendor/acer/a4/proprietary/libdiag.so:/system/lib/libdiag.so \
    vendor/acer/a4/proprietary/libdsi_netctrl.so:/system/lib/libdsi_netctrl.so \
    vendor/acer/a4/proprietary/libdsm.so:/system/lib/libdsm.so \
    vendor/acer/a4/proprietary/libdss.so:/system/lib/libdss.so \
    vendor/acer/a4/proprietary/libdsutils.so:/system/lib/libdsutils.so \
    vendor/acer/a4/proprietary/libgsdi_exp.so:/system/lib/libgsdi_exp.so \
    vendor/acer/a4/proprietary/libgstk_exp.so:/system/lib/libgstk_exp.so \
    vendor/acer/a4/proprietary/libidl.so:/system/lib/libidl.so \
    vendor/acer/a4/proprietary/libloc_api-rpc-qc.so:/system/lib/libloc_api-rpc-qc.so \
    vendor/acer/a4/proprietary/libmmgsdilib.so:/system/lib/libmmgsdilib.so \
    vendor/acer/a4/proprietary/libnv.so:/system/lib/libnv.so \
    vendor/acer/a4/proprietary/liboncrpc.so:/system/lib/liboncrpc.so \
    vendor/acer/a4/proprietary/libpbmlib.so:/system/lib/libpbmlib.so \
    vendor/acer/a4/proprietary/libpdapi.so:/system/lib/libpdapi.so \
    vendor/acer/a4/proprietary/libpdsm_atl.so:/system/lib/libpdsm_atl.so \
    vendor/acer/a4/proprietary/libqueue.so:/system/lib/libqueue.so \
    vendor/acer/a4/proprietary/libqdp.so:/system/lib/libqdp.so \
    vendor/acer/a4/proprietary/libqmi.so:/system/lib/libqmi.so \
    vendor/acer/a4/proprietary/libqmiservices.so:/system/lib/libqmiservices.so \
    vendor/acer/a4/proprietary/libril.so:/system/lib/libril.so \
    vendor/acer/a4/proprietary/libril-acer-1.so:/system/lib/libril-acer-1.so \
    vendor/acer/a4/proprietary/libril-acer-qmi-1.so:/system/lib/libril-acer-qmi-1.so \
    vendor/acer/a4/proprietary/libril-acerril-hook-oem.so:/system/lib/libril-acerril-hook-oem.so \
    vendor/acer/a4/proprietary/libwms.so:/system/lib/libwms.so \
    vendor/acer/a4/proprietary/libwmsts.so:/system/lib/libwmsts.so
# hw libs
PRODUCT_COPY_FILES += \
    vendor/acer/a4/proprietary/sensors.paso.so:/system/lib/hw/sensors.paso.so \
    vendor/acer/a4/proprietary/overlay.default.so:/system/lib/hw/overlay.default.so \
#EGL
PRODUCT_COPY_FILES += \
    vendor/acer/a4/proprietary/libEGL_adreno200.so:/system/lib/egl/libEGL_adreno200.so \
    vendor/acer/a4/proprietary/libGLESv1_CM_adreno200.so:/system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/acer/a4/proprietary/libGLESv2_adreno200.so:/system/lib/egl/libGLESv2_adreno200.so \
    vendor/acer/a4/proprietary/libq3dtools_adreno200.so:/system/lib/egl/libq3dtools_adreno200.so \
    vendor/acer/a4/proprietary/libgsl.so:/system/lib/libgsl.so 
# libs
PRODUCT_COPY_FILES += \
    vendor/acer/a4/proprietary/libaudioalsa.so:/system/lib/libaudioalsa.so \
    vendor/acer/a4/proprietary/libaudioeq.so:/system/lib/libaudioeq.so \
    vendor/acer/a4/proprietary/libcamera.so:/system/lib/libcamera.so \
    vendor/acer/a4/proprietary/libdivxdrmdecrypt.so:/system/lib/libdivxdrmdecrypt.so \
    vendor/acer/a4/proprietary/libDxAndroidSpecific.so:/system/lib/libDxAndroidSpecific.so \
    vendor/acer/a4/proprietary/libDxDrmCAPI.so:/system/lib/libDxDrmCAPI.so \
    vendor/acer/a4/proprietary/libDxDrmJava.so:/system/lib/libDxDrmJava.so \
    vendor/acer/a4/proprietary/libgemini.so:/system/lib/libgemini.so \
    vendor/acer/a4/proprietary/libmmipl.so:/system/lib/libmmipl.so \
    vendor/acer/a4/proprietary/libmm-abl.so:/system/lib/libmm-abl.so \
    vendor/acer/a4/proprietary/libmmjpeg.so:/system/lib/libmmjpeg.so \
    vendor/acer/a4/proprietary/libnetmgr.so:/system/lib/libnetmgr.so \
    vendor/acer/a4/proprietary/libOlaCameraJNI.so:/system/lib/libOlaCameraJNI.so \
    vendor/acer/a4/proprietary/libOlaEngine.so:/system/lib/libOlaEngine.so \
    vendor/acer/a4/proprietary/liboemcamera.so:/system/lib/liboemcamera.so \
    vendor/acer/a4/proprietary/liboverlay.so:/system/lib/liboverlay.so \
    vendor/acer/a4/proprietary/libpng.so:/system/lib/libpng.so \
    vendor/acer/a4/proprietary/libsensors_algos.so:/system/lib/libsensors_algos.so \
#omx
PRODUCT_COPY_FILES += \
    vendor/acer/a4/proprietary/libqcomm_omx.so:/system/lib/libqcomm_omx.so \
    vendor/acer/a4/proprietary/libOmxAacDec.so:/system/lib/libOmxAacDec.so \
    vendor/acer/a4/proprietary/libomx_aacdec_sharedlibrary.so:/system/lib/libomx_aacdec_sharedlibrary.so \
    vendor/acer/a4/proprietary/libOmxAacEnc.so:/system/lib/libOmxAacEnc.so \
    vendor/acer/a4/proprietary/libOmxAdpcmDec.so:/system/lib/libOmxAdpcmDec.so \
    vendor/acer/a4/proprietary/libOmxAmrDec.so:/system/lib/libOmxAmrDec.so \
    vendor/acer/a4/proprietary/libomx_amrdec_sharedlibrary.so:/system/lib/libomx_amrdec_sharedlibrary.so \
    vendor/acer/a4/proprietary/libOmxAmrEnc.so:/system/lib/libOmxAmrEnc.so \
    vendor/acer/a4/proprietary/libomx_amrenc_sharedlibrary.so:/system/lib/libomx_amrenc_sharedlibrary.so \
    vendor/acer/a4/proprietary/libOmxAmrRtpDec.so:/system/lib/libOmxAmrRtpDec.so \
    vendor/acer/a4/proprietary/libOmxAmrwbDec.so:/system/lib/libOmxAmrwbDec.so \
    vendor/acer/a4/proprietary/libomx_avcdec_sharedlibrary.so:/system/lib/libomx_avcdec_sharedlibrary.so \
    vendor/acer/a4/proprietary/libOmxEvrcDec.so:/system/lib/libOmxEvrcDec.so \
    vendor/acer/a4/proprietary/libOmxEvrcEnc.so:/system/lib/libOmxEvrcEnc.so \
    vendor/acer/a4/proprietary/libomx_m4vdec_sharedlibrary.so:/system/lib/libomx_m4vdec_sharedlibrary.so \
    vendor/acer/a4/proprietary/libomx_mp3dec_sharedlibrary.so:/system/lib/libomx_mp3dec_sharedlibrary.so \
    vendor/acer/a4/proprietary/libOmxMp3Dec.so:/system/lib/libOmxMp3Dec.so \
    vendor/acer/a4/proprietary/libOmxQcelp13Dec.so:/system/lib/libOmxQcelp13Dec.so \
    vendor/acer/a4/proprietary/libOmxQcelp13Enc.so:/system/lib/libOmxQcelp13Enc.so \
    vendor/acer/a4/proprietary/libomx_sharedlibrary.so:/system/lib/libomx_sharedlibrary.so \
    vendor/acer/a4/proprietary/libOmxWmaDec.so:/system/lib/libOmxWmaDec.so \
# binaries
PRODUCT_COPY_FILES += \
    vendor/acer/a4/proprietary/akmd8975:/system/bin/akmd8975 \
    vendor/acer/a4/proprietary/artagent:/system/bin/artagent \
    vendor/acer/a4/proprietary/athtestcmd:/system/bin/athtestcmd \
    vendor/acer/a4/proprietary/get_sensors_calib:/system/bin/get_sensors_calib \
    vendor/acer/a4/proprietary/get_wlan_mac:/system/bin/get_wlan_mac \
    vendor/acer/a4/proprietary/hci_qcomm_init:/system/bin/hci_qcomm_init \
    vendor/acer/a4/proprietary/hostapd:/system/bin/hostapd \
    vendor/acer/a4/proprietary/hostapd_cli:/system/bin/hostapd_cli \
    vendor/acer/a4/proprietary/hostapd_wps:/system/bin/hostapd_wps \
    vendor/acer/a4/proprietary/ip:/system/bin/ip \
    vendor/acer/a4/proprietary/mm-omx-devmgr:/system/bin/mm-omx-devmgr \
    vendor/acer/a4/proprietary/netmgrd:/system/bin/netmgrd \
    vendor/acer/a4/proprietary/port-bridge:/system/bin/port-bridge \
    vendor/acer/a4/proprietary/qmuxd:/system/bin/qmuxd \
    vendor/acer/a4/proprietary/wmiconfig:/system/bin/wmiconfig \
